spring.application.name=sistema_pedidos

spring.datasource.url=jdbc:postgresql://dpg-d7ps51pugtpc73b6v6fg-a:5432/pedidos_db_zbgj
spring.datasource.username=pedidos_db_zbgj_user
spring.datasource.password=yxk2TGPruMYEtRA8u4xWQbEJAkbCmQAo

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8080}